name: mapadirectsdk

excludeDir:
  - node_modules

# List of relative file/directory paths to copy and mirror in the generated documentation
# ALL LINK MUST BE RELATIVE TO THE doc/ FOLDER
assets:
  - ./src/assets/

# Default values for 202 sidebar theming
theme:
  logo: ./src/assets/img/logo.png
  css:
  sidebar:
    background: "#33363b"
    textColor: "#fff"

order:
  - Wrappers
