name: mapadirectsdk

excludeDir:
  - node_modules

# List of relative file/directory paths to copy and mirror in the generated documentation
assets:
  - ./doc/assets/

# Default values for 202 sidebar theming
theme:
  logo: ./doc/assets/logo.png
  css:
  sidebar:
    background: "#33363b"
    textColor: "#fff"

order:
  - Wrappers
