name: MapaDirect SDK

excludeDir:
  - node_modules

# List of relative file/directory paths to copy and mirror in the generated documentation
# ALL LINK MUST BE RELATIVE TO THE doc/ FOLDER
assets:
  - ./doc/assets/

# Default values for 202 sidebar theming
theme:
  logo: ./doc/assets/logo.png
  css:
  sidebar:
    background: "#33363b"
    textColor: "#fff"

order:
  - Introduction
  - Webservices products
  - Webservices Orders
  - Wrappers
  - Webhooks
  - Support
